### ISSUE TITLE
Exception handling when building driver cache in HardwareManager

### ISSUE THREAD

**Issue by aashah** [ColoradoSchoolOfMines/interface_sdk#1]
Currently, the HardwareManager builds a list of drivers that support a given functionality. Using that list, it attempts to cache an instance of each driver that it finds.

However, when any driver fails to instantiate (for whatever reason that may be), we throw an exception and stop attempting to cache drivers.

This is flawed, because realistically you may have two devices that support a functionality, but both will probably never be plugged in at the same time.

Proposed change:
Do not throw an exception when a driver fails to load.
Instead throw an exception when the driver cache is done being built, and we find that no drivers were loaded for the given functionality.

**Comment by muff1nman** [comment]
Finally fixed as of 23fb93f9b947961cbefdd1237aa125856e8c4940 (v0.2.0).
