### ISSUE TITLE
Processing 2.0 Support

### ISSUE THREAD

**Issue by muff1nman** [ColoradoSchoolOfMines/interface_sdk#11]
It would be nice to integrate processing 2.0 support and keep up to date with the aforementioned library

**Comment by muff1nman** [comment]
The interface sdk seems to work just fine with processing 2.0 614142f7f9b70686e257a5c07910151f4d5fe3fc

**Comment by muff1nman** [comment]
There is one big question to answer before this gets merged in:  What happens with modules developed with Processing 1.5.1?  A couple options:
1. Drop support for it completely
2. Create two different versions of the interfaceSDK, one for processing 1.5 and one for 2 and beyond
3. Create a backwards compatible `ProcessingModule` to support the older processing 1.5
4. Something we haven't considered

In my opinion 3 would be ideal because we could run modules using either version side by side, but it would also be very tricky with integrating the processing jar into the interface sdk.  If we went with this option we could no longer declare processing as a dependency in maven and would have to dynamically load the `core.jar` for processing dynamically based on the module being loaded (the module itself may be responsible for this?)

**Comment by ybakos** [comment]
I recommend dropping 1.x support and just focus on Processing 2.x.

**Comment by muff1nman** [comment]
Processing 2.1 support is now merged in.
