### ISSUE TITLE
Choose open source license

### ISSUE THREAD

**Issue by muff1nman** [ColoradoSchoolOfMines/interface_sdk#17]
We need to choose an open source license.

I would recommend one of the following in order of most restrictive to least restrictive
- gpl v3
- lgpl v3
- bsd

If you all want to chime in, that would be great and I would recommend doing some brief reading into some of these.  

I believe the biggest question is if we want to prevent commercial redistribution of our codebase.

**Comment by adiviness** [comment]
I think we should go with the GNU GPL. I don't know the difference between versions, I'd just like it to remain free/open software.

**Comment by muff1nman** [comment]
Added the license programatically to all source files using [this](https://code.google.com/p/maven-license-plugin/)

Note that the plugin added will [bind](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html) to the verify stage to check for updated licenses on all *.java files in the src/main/java and src/test/java subdirectories .  In other words, we will not typically run into this stage with `mvn package` as it comes into effect later and we will instead run into it when we run our `mvn deploy`.  With that said you can always run it manually with `mvn license:check` and to update the files use `mvn license:format`.  More information [here](https://code.google.com/p/maven-license-plugin/).
