### ISSUE TITLE
Wait on (y/n) prompt in install script

### ISSUE THREAD

**Issue by johkelly** [ColoradoSchoolOfMines/interface_sdk#24]
When the install script prompts the user whether it can install Java7 or the 32bit compatibility libraries on its own, it will immediately proceed when the user presses 'y' (and maybe 'n'), rather than waiting for them to confirm with enter.

Action: $> ${REPO_ROOT}/install/install.sh

Expected: 
$> Can I install {install dependency} (y/n)?
$> y
(wait for enter)
$> {install with spew}

Actual:
$> Can I install {install dependency} (y/n)?
$> y
$> {install with spew}

**Comment by muff1nman** [comment]
If you open up the script you can see the -y option passed to all the `sudo apt-gets`.  The reason for this was to make it so you can run the script without interacting with it.  How about another option if you want it to be interactive or not.  By default interactive?

**Comment by johkelly** [comment]
After poking a test script for a bit, the issue I was seeing was caused by the `-n 1` option on the `read` calls, which eats one character of input immediately. Letting it instead read an entire line of input and then parsing off the first char makes the prompts behave like apt-get calls where you have to hit enter to submit your response, rather than proceeding immediately after you type y.

I should be able to get a patch committed sometime this afternoon.

**Comment by muff1nman** [comment]
Good catch! Sounds good.
