### ISSUE TITLE
Cleanup After Install

### ISSUE THREAD

**Issue by johkelly** [ColoradoSchoolOfMines/interface_sdk#26]
Be a Good Neighbor(TM)

**Comment by muff1nman** [comment]
When you refer to cleanup do you mean to say that the 'kinect' directory should be deleted?

**Comment by johkelly** [comment]
That, and any other temporary directories that get created. I didn't have a chance to check what else the install script leaves behind in terms of directories/files.

This assuming, of course, that the ~/kinect/ directory is, in fact, not critical to have post-installation.

**Comment by muff1nman** [comment]
The ~/kinect directory is the only directory left behind.  There may be a couple reasons for leaving it behind.  
1. so you can test the kinect on the openni samples.  
2. so you can run `make uninstall`.  

Again ideally when we get an actual package setup (Ill make an issue for this (UPDATE: #27)), we wont have to worry about 2 and can just let the package manager deal with uninstalling.

How about a compromise.  We will make it an option to keep the ~/kinect directory around.  By default we will remove it.  

Eh?

**Comment by johkelly** [comment]
1 is nice to have, but 2 sounds like a really good thing to keep around in some form. If there's no way to isolate the Makefile for uninstallation, I think making it very clear to the user that a `~/kinect` directory has been created is a better option than removing it.

**Comment by muff1nman** [comment]
I would be hesitant to try to separate out the makefile.  Lets shoot for
just informing the user first.

**Comment by muff1nman** [comment]
See 00eeae06ef9fd63aa2d5d00206c855708e115cca
