### ISSUE TITLE
Refactor Interface for drivers

### ISSUE THREAD

**Issue by muff1nman** [ColoradoSchoolOfMines/interface_sdk#38]
- Minimalize constructor duties
  - put that inside a different function (that has a nice name)

**Comment by MattWesemann** [comment]
Should we have any sort of protection on the interface methods to prevent people from calling them without first calling the separate function to finish loading the driver? I think it would be a good idea. What I am thinking is a new exception "NotLoadedException" that on each function we check to see if the driver has been loaded and if false we throw the exception. This way we don't have to worry about people calling those functions before the parameters get initialized. It will clutter up the code a little as now there is another exception to catch as well as making each of the functions longer, but I feel it may be a good tradeoff. 

Thoughts?
